#!/bin/bash

#
# Problem with this is that it needs to know the UID! It calls getpwnam
# for user names on "uid=xxx" and that's local only. I'm using the actual
# integer ID for jcf12, which I hope is the same across the university.

# Of course, I need to be on the VPN so it can't work from inside Hecate's
# virtualised Linux box.

# On windows:
#   \\sitehost.disk.aber.ac.uk\pcot-aber-ac-uk
#   NOTE BACKSLASHES!!
# That doesn't bloody work either.

sudo mount -t cifs -o rw,username=jcf12,uid=6319 \
    //sitehost.disk.aber.ac.uk/pcot-aber-ac-uk mnt
    
echo "Mounted on mnt"
