site_name: PCOT Cookbook

theme: 
  name: material
  language: en
  palette:
    scheme: slate
    primary: red
    accent: pink
  features:
    - navigation.tabs
    
nav:
    - Introduction: 'index.md'
    - PCOT details: 'pcot.md'
    - Camera data: 'cameras/index.md'
    - Recipes:
        - recipes/spectrum.md
        - recipes/parametermap.md
        - recipes/spectralon.md
        - recipes/combined.md
        - recipes/flatfield.md
        - recipes/calibration.md
        - recipes/assignfilters.md

markdown_extensions:
    - attr_list
    - lightbox:LightBoxExtension # lightbox images with ![!Caption](img.png)
    - admonition
    - footnotes
    - pymdownx.arithmatex # permits $..$ and \[ .. \] for maths; \begin{..}..\end{..} works too
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
    - search
    - mermaid2


extra_javascript:
    - js/lightbox-plus-jquery.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
    - css/lightbox.min.css
