#!/bin/bash

ip=$(ip -o -4 addr show enp0s8 | awk '{print $4}' | cut -d/ -f1)

echo Binding to $ip

export PYTHONPATH="../PCOT-Cookbook"
conda run -n mkdocs --no-capture-output mkdocs serve -a $ip:1313
